version: "3.8"

services:
  accounts:
    image: kishorevbhosale/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - sknetwork

  cards:
    image: kishorevbhosale/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - sknetwork

  loans:
    image: kishorevbhosale/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - sknetwork

networks:
  sknetwork: